### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by ArneBachmann** [Sipkab/jvm-tail-recursion#5]
Are there any benchmarks showing the effect of applying the tail-recursion optimizations?

**Comment by Sipkab** [comment]
Not yet. I also wanted to make some but haven't got the time to get to it.

I shall get to it in the following days. If you have any snippets that you want to measure, feel free to post them.

**Comment by Sipkab** [comment]
Made some benchmarks for some simple scenarios. The results are available in the README for the [benchmark directory](https://github.com/Sipkab/jvm-tail-recursion/tree/master/benchmark).

If you have any further ideas for methods that could be benchmarked, feel free to send them.
